#!/usr/bin/env node
/**
 * dev-hosted.mjs — run the OpenSight API in hosted mode locally for development.
 *
 * Starts a real hosted-mode API (email/password + TOTP auth, tenant isolation) against a
 * local SQLite metadata database, provisions a dev tenant and admin user from `.env`,
 * and serves the built web client on the same origin so the browser passes the
 * server's host/origin checks.
 *
 * Usage: `npm run dev:hosted` from the repo root.
 *
 * First run generates `.env` (gitignored — never commit it) with fresh dev keys and
 * prints the TOTP setup URI for the dev admin. Scan it with any authenticator app.
 * Subsequent runs reuse the existing `.env` and database.
 *
 * This is for local development and UI testing only. The http://localhost origin is
 * accepted by hosted-config.ts under a documented loopback exception (RFC 8252 §7.3).
 */

import { readFile, writeFile, mkdir, stat } from 'node:fs/promises';
import { createServer } from 'node:http';
import { randomBytes } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { join, dirname, extname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..', '..');
const envPath = join(root, '.env');

function parseEnv(text) {
  const out = {};
  for (const line of text.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq < 0) continue;
    let value = trimmed.slice(eq + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) value = value.slice(1, -1);
    out[trimmed.slice(0, eq).trim()] = value;
  }
  return out;
}

const b64 = () => randomBytes(32).toString('base64');
const tenantLimits = { running: 1, queued: 4, executionMs: 10000, queueMs: 30000, sourceRows: 100000, resultBytes: 1048576, workingBytes: 16777216, cacheBytes: 16777216, workerRssBytes: 536870912, workerHeapMb: 128, duckdbMemoryMb: 64, cellChars: 16384 };
const nodeLimits = { ...tenantLimits, running: 3, queued: 12, refreshSlots: 1, workingBytes: 67108864, cacheBytes: 67108864, workerRssBytes: 1610612736 };

async function loadEnv() {
  let file = {};
  try { file = parseEnv(await readFile(envPath, 'utf8')); } catch { /* generated below */ }
  const generated = !file.OPENSIGHT_AUTH_SIGNING_KEY;
  const env = {
    OPENSIGHT_MODE: 'hosted',
    OPENSIGHT_PUBLIC_ORIGIN: 'http://localhost:3001',
    OPENSIGHT_AUTH_ISSUER: 'opensight-dev',
    OPENSIGHT_AUTH_AUDIENCE: 'opensight-dev-api',
    OPENSIGHT_AUTH_KEY_ID: 'dev-key',
    OPENSIGHT_AUTH_SIGNING_KEY: file.OPENSIGHT_AUTH_SIGNING_KEY ?? b64(),
    OPENSIGHT_AUTH_ENCRYPTION_KEY: file.OPENSIGHT_AUTH_ENCRYPTION_KEY ?? b64(),
    OPENSIGHT_OPERATOR_KEY: file.OPENSIGHT_OPERATOR_KEY ?? b64(),
    OPENSIGHT_SESSION_SECONDS: file.OPENSIGHT_SESSION_SECONDS ?? '3600',
    OPENSIGHT_INVITATION_SECONDS: '86400',
    OPENSIGHT_METADATA_DATABASE: file.OPENSIGHT_METADATA_DATABASE ?? '.opensight/dev-hosted.sqlite',
    OPENSIGHT_NODE_LIMITS: file.OPENSIGHT_NODE_LIMITS ?? JSON.stringify(nodeLimits),
    OPENSIGHT_TENANT_LIMIT_DEFAULTS: file.OPENSIGHT_TENANT_LIMIT_DEFAULTS ?? JSON.stringify(tenantLimits),
    OPENSIGHT_TENANT_LIMIT_OVERRIDES: file.OPENSIGHT_TENANT_LIMIT_OVERRIDES ?? '{}',
    OPENSIGHT_DEV_EMAIL: file.OPENSIGHT_DEV_EMAIL ?? 'dev@opensight.local',
    OPENSIGHT_DEV_PASSWORD: file.OPENSIGHT_DEV_PASSWORD ?? randomBytes(12).toString('base64url'),
    OPENSIGHT_DEV_NAME: file.OPENSIGHT_DEV_NAME ?? 'Dev Admin',
    OPENSIGHT_DEV_TENANT: file.OPENSIGHT_DEV_TENANT ?? 'Dev tenant',
    OPENSIGHT_DEV_TOTP_URI: file.OPENSIGHT_DEV_TOTP_URI ?? '',
  };
  // The three keys must be pairwise distinct (the validator enforces this).
  while (env.OPENSIGHT_AUTH_ENCRYPTION_KEY === env.OPENSIGHT_AUTH_SIGNING_KEY) env.OPENSIGHT_AUTH_ENCRYPTION_KEY = b64();
  while (env.OPENSIGHT_OPERATOR_KEY === env.OPENSIGHT_AUTH_SIGNING_KEY || env.OPENSIGHT_OPERATOR_KEY === env.OPENSIGHT_AUTH_ENCRYPTION_KEY) env.OPENSIGHT_OPERATOR_KEY = b64();
  if (generated) {
    const lines = ['# OpenSight local hosted-mode development credentials. DO NOT COMMIT.', '# Generated by `npm run dev:hosted`. Delete this file to regenerate.'];
    for (const [k, v] of Object.entries(env)) if (k !== 'OPENSIGHT_MODE') lines.push(`${k}=${v}`);
    await writeFile(envPath, lines.join('\n') + '\n', { mode: 0o600 });
    console.log(`Generated ${envPath} (mode 600, gitignored).`);
  }
  return { env, generated };
}

async function newestMtime(dir) {
  let newest = 0;
  const { readdir } = await import('node:fs/promises');
  async function walk(d) {
    for (const entry of await readdir(d, { withFileTypes: true })) {
      if (entry.name === 'node_modules' || entry.name === 'dist') continue;
      const p = join(d, entry.name);
      if (entry.isDirectory()) await walk(p);
      else { const s = await stat(p).catch(() => null); if (s && s.mtimeMs > newest) newest = s.mtimeMs; }
    }
  }
  await walk(dir).catch(() => {});
  return newest;
}

async function ensureBuilt() {
  const targets = [
    [join(root, 'packages/api/dist/cli.js'), '@opensight/api', join(root, 'packages/api/src')],
    [join(root, 'packages/web/dist/index.html'), '@opensight/web', join(root, 'packages/web/src')],
  ];
  for (const [file, workspace, srcDir] of targets) {
    let build = false;
    try {
      const out = await stat(file);
      if (await newestMtime(srcDir) > out.mtimeMs) { console.log(`${workspace} sources are newer than dist — rebuilding…`); build = true; }
    } catch { build = true; }
    if (!build) continue;
    console.log(`Building ${workspace}…`);
    const result = spawnSync('npm', ['run', 'build', `--workspace=${workspace}`], { cwd: root, stdio: 'inherit', shell: process.platform === 'win32' });
    if (result.status !== 0) throw new Error(`build failed for ${workspace}`);
  }
}

const MIME = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.json': 'application/json', '.svg': 'image/svg+xml', '.png': 'image/png', '.ico': 'image/x-icon', '.woff2': 'font/woff2', '.map': 'application/json' };

async function main() {
  const { env } = await loadEnv();
  Object.assign(process.env, env);
  await ensureBuilt();

  const { SqliteMetadataDatabase } = await import('./dist/metadata-db.js');
  const { initializeMetadata } = await import('./dist/metadata-schema.js');
  const { initializeAuth } = await import('./dist/auth-schema.js');
  const { hostedConfig } = await import('./dist/hosted-config.js');
  const { budgetEnvironment, migrateBudgets } = await import('./dist/budget-store.js');
  const { HostedAuth } = await import('./dist/hosted-auth.js');
  const { HostedProvisioning } = await import('./dist/hosted-provisioning.js');
  const { totp } = await import('./dist/auth-crypto.js');
  const { createBuiltinHostedServer } = await import('./dist/hosted-server.js');

  const dbPath = resolve(root, env.OPENSIGHT_METADATA_DATABASE);
  await mkdir(dirname(dbPath), { recursive: true });
  const db = new SqliteMetadataDatabase(dbPath);
  await initializeMetadata(db);
  await initializeAuth(db);
  await migrateBudgets(db, budgetEnvironment(env), 'frozen');
  const config = hostedConfig(env);

  // Provision the dev tenant + admin unless the dev identity already exists and is active.
  const existing = await db.transaction(c => c.query('SELECT subject, status FROM h2_identities WHERE email = ?', [env.OPENSIGHT_DEV_EMAIL]));
  let tenantId, totpUri;
  if (existing.length && existing[0].status === 'active') {
    tenantId = String((await db.transaction(c => c.query('SELECT tenant_id FROM h2_memberships WHERE subject = ? LIMIT 1', [existing[0].subject])))[0]?.tenant_id ?? '');
    console.log(`Dev user ${env.OPENSIGHT_DEV_EMAIL} already enrolled.`);
  } else {
    const sent = [];
    const mail = { configured: true, async send(message) { sent.push(message); } };
    const provisioning = new HostedProvisioning(db, config, mail);
    const auth = await HostedAuth.create(db, config);
    const result = await provisioning.provision('dev-hosted', { name: env.OPENSIGHT_DEV_TENANT, administrator: { email: env.OPENSIGHT_DEV_EMAIL, name: env.OPENSIGHT_DEV_NAME } });
    tenantId = result.tenantId;
    const invitation = sent[0].html.match(/<code>([^<]+)<\/code>/)[1];
    const enrollment = await auth.enroll(invitation, env.OPENSIGHT_DEV_PASSWORD, 'local');
    totpUri = enrollment.uri;
    // Complete enrollment with a fresh TOTP code so the account is ready to sign in.
    const decode32 = s => { let bits = 0, acc = 0; const bytes = []; for (const ch of s) { acc = (acc << 5) | 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'.indexOf(ch); bits += 5; if (bits >= 8) { bits -= 8; bytes.push((acc >>> bits) & 255); } } return Buffer.from(bytes); };
    await auth.accept(invitation, env.OPENSIGHT_DEV_PASSWORD, totp(decode32(enrollment.secret), Math.floor(Date.now() / 30000)), 'local');
    console.log(`Provisioned tenant ${tenantId} and enrolled ${env.OPENSIGHT_DEV_EMAIL}.`);
    // Persist the TOTP URI so later runs can print it without re-enrolling.
    await writeFile(envPath, (await readFile(envPath, 'utf8')) + `OPENSIGHT_DEV_TOTP_URI=${totpUri}\n`);
  }
  const printedTotpUri = totpUri ?? env.OPENSIGHT_DEV_TOTP_URI;

  const api = await createBuiltinHostedServer({ membershipDatabase: db, tenantDatabase: db, env });
  const webDist = join(root, 'packages/web/dist');

  const server = createServer(async (req, res) => {
    try {
      const url = new URL(req.url ?? '/', 'http://localhost');
      if (url.pathname === '/api' || url.pathname.startsWith('/api/')) {
        // The web client prefixes its base (/api) onto API routes (/api/…) — strip one level.
        req.url = url.pathname.replace(/^\/api/, '') + url.search;
        api.emit('request', req, res);
        return;
      }
      let path = url.pathname === '/' ? '/index.html' : url.pathname;
      let file;
      try { file = await readFile(join(webDist, path)); }
      catch { file = await readFile(join(webDist, 'index.html')); path = '/index.html'; }
      res.writeHead(200, { 'Content-Type': MIME[extname(path)] ?? 'application/octet-stream', 'Cache-Control': 'no-store' });
      res.end(file);
    } catch (error) {
      res.writeHead(500, { 'Content-Type': 'text/plain' });
      res.end('dev-hosted error');
    }
  });

  const port = Number(new URL(env.OPENSIGHT_PUBLIC_ORIGIN).port || 3000);
  server.listen(port, '127.0.0.1', () => {
    console.log('');
    console.log(`OpenSight hosted dev server: ${env.OPENSIGHT_PUBLIC_ORIGIN}`);
    console.log(`  Workspace ID: ${tenantId}`);
    console.log(`  Email:        ${env.OPENSIGHT_DEV_EMAIL}`);
    console.log(`  Password:     ${env.OPENSIGHT_DEV_PASSWORD}`);
    if (printedTotpUri) {
      console.log('');
      console.log('  TOTP setup URI (scan with your authenticator app, first run only):');
      console.log(`  ${printedTotpUri}`);
    }
    console.log('');
    console.log('Local-only credentials from .env (gitignored). Ctrl+C to stop.');
  });
}

main().catch(error => { console.error(error instanceof Error ? error.message : error); process.exit(1); });
