import { spawn } from 'node:child_process';
import { createServer } from 'node:net';
import { request as httpRequest } from 'node:http';
import { once } from 'node:events';
import { environment } from './hosted-helpers.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID, randomBytes } from 'node:crypto';
import { mkdtemp, rm, readdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { performance } from 'node:perf_hooks';
import { Pool } from 'pg';
import { PostgresMetadataDatabase } from '../dist/metadata-db.js';
import { ReferencePostgres, migrateReference } from '../dist/single-node.js';
import { ReferenceMaintenance } from '../dist/single-node-maintenance.js';
import { HostedUsage } from '../dist/hosted-usage.js';
import { MetadataOperator } from '../dist/metadata-operator.js';
import { TenantMetadata } from '../dist/metadata.js';
import { hostedReadiness } from '../dist/hosted-health.js';
import { referenceEnv } from './h8-helpers.mjs';
import { seedSources } from './source-helpers.mjs';

test('H8 live Postgres fresh install/migrate/restart/restore/deletion, single-node lock and competing tenant drill', { skip: process.env.DATABASE_URL ? false : 'DATABASE_URL is not set' }, async t => {
  const prefix = `h8_${randomUUID().replaceAll('-', '')}`, role = `${prefix}_tenant`, schema = `${prefix}_live`, restored = `${prefix}_restore`;
  const admin = new Pool({ connectionString: process.env.DATABASE_URL }); let reference, second, targetPool;
  const dir = await mkdtemp(join(tmpdir(), 'h8-pg-')), key = randomBytes(32);
  t.after(async () => {
    await second?.close(); await reference?.close(); await targetPool?.end();
    await admin.query(`DROP SCHEMA IF EXISTS ${restored} CASCADE`); await admin.query(`DROP SCHEMA IF EXISTS ${schema} CASCADE`); await admin.query(`DROP ROLE IF EXISTS ${role}`); await admin.end(); await rm(dir, { recursive: true, force: true });
  });
  await admin.query(`CREATE SCHEMA ${schema}`); await admin.query(`CREATE SCHEMA ${restored}`);
  await admin.query(`CREATE ROLE ${role} LOGIN NOINHERIT NOSUPERUSER NOBYPASSRLS`);
  await admin.query(`GRANT USAGE ON SCHEMA ${schema} TO ${role}`);
  const operatorUrl = new URL(process.env.DATABASE_URL); operatorUrl.searchParams.set('options', `-c search_path=${schema}`);
  const tenantUrl = new URL(operatorUrl); tenantUrl.username = role; tenantUrl.password = '';
  const env = { ...referenceEnv, OPENSIGHT_POSTGRES_OPERATOR_URL: operatorUrl.href, OPENSIGHT_POSTGRES_TENANT_URL: tenantUrl.href };
  reference = new ReferencePostgres(env); await reference.lock(() => assert.fail('unexpected lost lock'));
  second = new ReferencePostgres(env); await assert.rejects(second.lock(() => {}), { code: 'REFERENCE_ALREADY_RUNNING' }); await second.close(); second = undefined;
  const started = performance.now();
  await migrateReference(reference.operator, env); await reference.grantTenant(); await migrateReference(reference.operator, env); await reference.grantTenant();
  await hostedReadiness(reference.operator, reference.tenant);
  // The executable harness also migrates, starts and drains using real separate pools.
  await reference.close(); reference = undefined;
  const cliEnv = { ...process.env, ...environment(), ...env, HOST: '127.0.0.1' };
  const cli = new URL('../dist/single-node-cli.js', import.meta.url).pathname;
  const migration = spawn(process.execPath, [cli, 'migrate'], { env: cliEnv, stdio: ['ignore', 'pipe', 'pipe'] });
  let migrationOutput = ''; migration.stdout.on('data', b => { migrationOutput += b; }); migration.stderr.on('data', b => { migrationOutput += b; });
  assert.equal((await once(migration, 'exit'))[0], 0, migrationOutput);
  const reservation = createServer(); await new Promise(r => reservation.listen(0, '127.0.0.1', r));
  const port = reservation.address().port; await new Promise(r => reservation.close(r));
  const child = spawn(process.execPath, [cli, 'serve'], { env: { ...cliEnv, PORT: String(port) }, stdio: ['ignore', 'pipe', 'pipe'] });
  t.after(() => { if (child.exitCode === null) child.kill('SIGKILL'); });
  let output = '';
  await new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(Error('reference start timeout')), 15000);
    child.stdout.on('data', b => { output += b; if (output.includes('Actual deployment requires separate authorization.')) { clearTimeout(timer); resolve(); } });
    child.once('exit', () => { clearTimeout(timer); reject(Error('reference exited before listening')); });
  });
  const status = await new Promise((resolve, reject) => {
    const request = httpRequest({ port, host: '127.0.0.1', path: '/readyz', headers: { host: 'opensight.example', authorization: `Operator ${Buffer.from(cliEnv.OPENSIGHT_OPERATOR_KEY, 'base64').toString('base64url')}` } }, response => { response.resume(); response.once('end', () => resolve(response.statusCode)); });
    request.on('error', reject); request.end();
  });
  assert.equal(status, 200); child.kill('SIGTERM'); assert.equal((await once(child, 'exit'))[0], 0);
  assert.match(output, /Pilot, single-node, no HA claims/);
  reference = new ReferencePostgres(env); await reference.lock(() => {});
  for (const table of ['h8_usage', 'h8_usage_events', 'h8_audit', 'h2_identities', 'h7_jobs']) await assert.rejects(reference.tenantPool.query(`SELECT * FROM ${table}`), { code: '42501' });
  await assert.rejects(reference.tenantPool.query('DELETE FROM h1_outbox'), { code: '42501' });
  await assert.rejects(reference.tenantPool.query("UPDATE h1_outbox SET event_type = 'forged'"), { code: '42501' });
  await seedSources(reference.operator);
  const usageConfig = { defaults: { apiCalls: 8, storageBytes: 100000, computeAttempts: 2 }, tenants: {} };
  const usage = new HostedUsage(reference.operator, usageConfig), metadata = new TenantMetadata(reference.tenant, reference.operator, usage);
  const one = await metadata.authenticate(null, async () => ({ namespaceId: 'one', userId: 'admin' })), two = await metadata.authenticate(null, async () => ({ namespaceId: 'two', userId: 'admin' }));
  const loadStart = performance.now();
  const outcomes = await Promise.allSettled(Array.from({ length: 64 }, (_, i) => usage.consume(metadata, i % 2 ? one : two, 'apiCalls')));
  assert.equal(outcomes.filter(r => r.status === 'fulfilled').length, 16);
  assert.equal(outcomes.filter(r => r.status === 'rejected' && r.reason.code === 'USAGE_LIMIT_EXCEEDED').length, 48);
  const loadMs = Math.round(performance.now() - loadStart);
  await assert.rejects(usage.consume(metadata, { ...one, tenantId: two.tenantId }, 'apiCalls'), { code: 'TENANT_CONTEXT_REQUIRED' });
  await metadata.put(one, { kind: 'group', id: 'same' }, { name: 'One', userIds: [] });
  await assert.rejects(metadata.get(two, { kind: 'group', id: 'same' }), { code: 'RESOURCE_NOT_FOUND' });
  // Reopen real pools and retain counters, resources and audit across restart.
  await reference.close(); reference = new ReferencePostgres(env); await reference.lock(() => {});
  await hostedReadiness(reference.operator, reference.tenant);
  const resumedUsage = new HostedUsage(reference.operator, usageConfig), resumedMetadata = new TenantMetadata(reference.tenant, reference.operator, resumedUsage);
  const current = await resumedMetadata.authenticate(null, async () => ({ namespaceId: 'one', userId: 'admin' }));
  await assert.rejects(resumedUsage.consume(resumedMetadata, current, 'apiCalls'), { code: 'USAGE_LIMIT_EXCEEDED' });
  const maintenance = await ReferenceMaintenance.open(reference.operator, join(dir, 'backups'), key, 'frozen');
  const backup = await maintenance.backup();
  const targetUrl = new URL(operatorUrl); targetUrl.searchParams.set('options', `-c search_path=${restored}`);
  targetPool = new Pool({ connectionString: targetUrl.href }); const target = new PostgresMetadataDatabase(targetPool);
  await migrateReference(target, referenceEnv);
  const recovery = await ReferenceMaintenance.open(target, join(dir, 'backups'), key, 'frozen'); await recovery.restore(backup.id);
  assert.equal((await new MetadataOperator(target).tenant('tenant-one')).state, 'suspended');
  assert.equal((await target.transaction(c => c.query("SELECT * FROM h1_resources WHERE kind = 'group'"))).length, 1);
  const op = new MetadataOperator(reference.operator); await op.transition('delete-one', 'tenant-one', 'delete', (await op.tenant('tenant-one')).version);
  await maintenance.deleteTenant('delete-one', 'none');
  assert.deepEqual(await readdir(join(dir, 'backups')), ['registry']);
  assert.equal((await op.tenant('tenant-one')).state, 'deleted'); assert.equal((await op.tenant('tenant-two')).state, 'active');
  await assert.rejects(recovery.restore(backup.id), { code: 'BACKUP_UNREGISTERED' });
  t.diagnostic(`H8 PostgreSQL: 64 concurrent admissions, 16 accepted, 48 denied, ${loadMs} ms; ${backup.rows} backup rows, ${backup.bytes} encrypted bytes; complete drill ${Math.round(performance.now() - started)} ms`);
});
