import test from 'node:test';
import assert from 'node:assert/strict';
import { act, createElement } from 'react';
import { create } from 'react-test-renderer';
import { LiveAuthorVisual } from '../build/test/LiveAuthorVisual.js';
import { VisualCard } from '../build/test/VisualCard.js';
import { activeSheet, authorReducer, emptyDraft } from '../build/test/authoring.js';
import { withActionFilters } from '../build/test/interactions.js';
test('actions and clearing debounce, hide stale results, cancel superseded queries and reject late errors', async t => {
  const old = globalThis.IS_REACT_ACT_ENVIRONMENT; globalThis.IS_REACT_ACT_ENVIRONMENT = true;
  t.mock.timers.enable({ apis: ['setTimeout'] });
  let d = authorReducer(emptyDraft(), { type: 'add', kind: 'bar' });
  d = authorReducer(d, { type: 'filter-actions', actions: [{ id: 'a', name: 'Filter', sourceField: 'region', targets: 'all', mappings: {} }] });
  d = authorReducer(d, { type: 'add', kind: 'table' });
  const s = activeSheet(d), [source, target] = s.visuals, requests = [];
  const client = { queryDataset: (_, query, signal) => new Promise((resolve, reject) => requests.push({ query, signal, resolve, reject })) };
  const render = value => createElement(LiveAuthorVisual, { client, interactive: true, calculations: [], visual: withActionFilters(s, target, value ? { [source.id]: { values: { region: value } } } : {}) });
  let renderer; await act(() => { renderer = create(render()); });
  t.after(async () => { await act(() => renderer.unmount()); globalThis.IS_REACT_ACT_ENVIRONMENT = old; });
  const card = () => renderer.root.findByType(VisualCard).props;
  await act(() => t.mock.timers.tick(250));
  await act(() => requests[0].resolve({ rows: [{ region: 'East', revenue: 500 }, { region: 'West', revenue: 400 }] }));
  await act(() => renderer.update(render('East'))); assert.equal(card().visual.rows, null); assert.equal(card().loading, true);
  await act(() => t.mock.timers.tick(100)); await act(() => renderer.update(render('West')));
  await act(() => t.mock.timers.tick(249)); assert.equal(requests.length, 1);
  await act(() => t.mock.timers.tick(1)); assert.equal(requests.length, 2);
  await act(() => renderer.update(render())); assert.equal(card().visual.rows, null); assert.ok(requests[1].signal.aborted);
  await act(() => t.mock.timers.tick(250)); assert.equal(requests[2].query.filters.length, 0);
  await act(() => requests[2].resolve({ rows: [{ region: 'East', revenue: 500 }, { region: 'West', revenue: 400 }] }));
  await act(() => requests[1].reject(new Error('Late failure'))); assert.equal(card().visual.rows.length, 2); assert.equal(card().dataMessage, undefined);
});
