import test from 'node:test';
import assert from 'node:assert/strict';
import { act, createElement } from 'react';
import { create } from 'react-test-renderer';
import { LiveAuthorVisual, PARAMETER_DEBOUNCE_MS } from '../build/test/LiveAuthorVisual.js';
import { VisualCard } from '../build/test/VisualCard.js';
import { activeSheet, authorReducer, emptyDraft } from '../build/test/authoring.js';
const visual = activeSheet(authorReducer(emptyDraft(), { type: 'add', kind: 'kpi' })).visuals[0];
const parameter = { id: 'parameter-1', name: 'Region', type: 'string', multiple: false, values: ['East'], defaultValues: ['East'] };
const affected = { ...visual, filters: [{ columnName: 'region', parameterName: 'Region', values: [] }] };
test('parameter requests debounce, clear stale data immediately and discard late responses/errors', async t => {
  const old = globalThis.IS_REACT_ACT_ENVIRONMENT; globalThis.IS_REACT_ACT_ENVIRONMENT = true;
  t.mock.timers.enable({ apis: ['setTimeout'] });
  const requests = [], client = { queryDataset: (_, query, signal) => new Promise((resolve, reject) => requests.push({ query, signal, resolve, reject })) };
  let renderer;
  const render = values => createElement(LiveAuthorVisual, { visual: affected, calculations: [], parameters: [{ ...parameter, values }], client });
  await act(() => { renderer = create(render(['East'])); });
  t.after(async () => { await act(() => renderer.unmount()); globalThis.IS_REACT_ACT_ENVIRONMENT = old; });
  const card = () => renderer.root.findByType(VisualCard).props;
  assert.equal(card().loading, true); assert.equal(card().visual.rows, null); assert.equal(requests.length, 0);
  await act(() => t.mock.timers.tick(PARAMETER_DEBOUNCE_MS)); assert.equal(requests.length, 1);
  await act(() => requests[0].resolve({ rows: [{ revenue: 500 }] })); assert.deepEqual(card().visual.rows, [{ revenue: 500 }]);
  await act(() => renderer.update(render(['West'])));
  assert.equal(card().loading, true); assert.equal(card().visual.rows, null); assert.ok(requests[0].signal.aborted);
  await act(() => t.mock.timers.tick(100));
  await act(() => renderer.update(render(['East'])));
  await act(() => t.mock.timers.tick(249)); assert.equal(requests.length, 1);
  await act(() => t.mock.timers.tick(1)); assert.equal(requests.length, 2);
  await act(() => renderer.update(render(['West'])));
  await act(() => t.mock.timers.tick(250)); assert.equal(requests.length, 3);
  await act(() => requests[2].resolve({ rows: [{ revenue: 400 }] }));
  await act(() => requests[1].resolve({ rows: [{ revenue: 999 }] }));
  assert.deepEqual(card().visual.rows, [{ revenue: 400 }]);
  await act(() => renderer.update(render(['Missing'])));
  assert.equal(card().visual.rows, null);
  await act(() => t.mock.timers.tick(250));
  await act(() => requests[3].reject(new Error('API unavailable')));
  assert.equal(card().loading, false); assert.equal(card().visual.rows, null); assert.equal(card().dataMessage, 'API unavailable');
});
test('unrelated parameter changes and display edits do not requery an unaffected visual; changing client invalidates results', async t => {
  const old = globalThis.IS_REACT_ACT_ENVIRONMENT; globalThis.IS_REACT_ACT_ENVIRONMENT = true;
  let count = 0, renderer;
  const client = { queryDataset: async () => { count++; return { rows: [{ revenue: 900 }] }; } };
  const render = (parameters, item = visual, c = client) => createElement(LiveAuthorVisual, { visual: item, calculations: [], parameters, client: c });
  await act(() => { renderer = create(render([parameter])); });
  t.after(async () => { await act(() => renderer.unmount()); globalThis.IS_REACT_ACT_ENVIRONMENT = old; });
  await act(() => renderer.update(render([{ ...parameter, values: ['West'] }], { ...visual, title: 'Edited' })));
  assert.equal(count, 1);
  await act(() => renderer.update(render([parameter], visual, { queryDataset: () => new Promise(() => {}) })));
  const card = renderer.root.findByType(VisualCard).props;
  assert.equal(card.loading, true); assert.equal(card.visual.rows, null);
});
