/** Supported bundle shapes. Unknown native options remain fail-closed in the compiler. */
export const EXTRA_VISUALS = {
  sankey: { variant: 'sankeyDiagramVisual', wells: 'sankeyDiagramAggregatedFieldWells', dimensions: ['source', 'destination'], measures: ['weight'], label: 'Sankey', icon: '⇶', note: 'One source dimension, one destination dimension and one nonnegative weight measure. Duplicate source→destination pairs are summed. Equal values share a node across both wells. Cycles and all-zero flows are unsupported.' },
  radar: { variant: 'radarChartVisual', wells: 'radarChartAggregatedFieldWells', dimensions: ['category', 'color'], measures: ['values'], label: 'Radar', icon: '⬡', note: 'One category dimension sets the axes; one or more measures draw the polygons; an optional second dimension splits series by color. Axes scale independently; nulls remain gaps.' },
  scatter: { variant: 'scatterPlotVisual', wells: 'scatterPlotCategoricallyAggregatedFieldWells', dimensions: ['category'], measures: ['xAxis', 'yAxis', 'size'], label: 'Scatter plot', icon: '⠿', note: 'One point per supplied group; X and Y measures required, optional third measure sets size.' },
  combo: { variant: 'comboChartVisual', wells: 'comboChartAggregatedFieldWells', dimensions: ['category'], measures: ['barValues', 'lineValues'], label: 'Combo', icon: '▥⌁', note: 'First measure is a bar; remaining measures are lines on the same value axis.' },
  bar100: { variant: 'barChartVisual', wells: 'barChartAggregatedFieldWells', dimensions: ['category'], measures: ['values'], label: '100% stacked bar', icon: '▥%', note: 'Nonnegative measures normalized to 100% within each category; zero totals remain zero.' },
  area: { variant: 'lineChartVisual', wells: 'lineChartAggregatedFieldWells', dimensions: ['category'], measures: ['values'], label: 'Area', icon: '◩', note: 'Area under each measure; null values remain gaps.' },
  funnel: { variant: 'funnelChartVisual', wells: 'funnelChartAggregatedFieldWells', dimensions: ['category'], measures: ['values'], label: 'Funnel', icon: '▽', note: 'One nonnegative measure per stage, in supplied or explicitly sorted order.' },
  gauge: { variant: 'gaugeChartVisual', wells: '', dimensions: [], measures: ['values'], label: 'Gauge', icon: '◴', note: 'A single measure and one aggregate row. Set the minimum and maximum in Properties.' },
  treemap: { variant: 'treeMapVisual', wells: 'treeMapAggregatedFieldWells', dimensions: ['groups'], measures: ['sizes'], label: 'Treemap', icon: '▧', note: 'One or more group levels and one nonnegative size measure.' },
  heatmap: { variant: 'heatMapVisual', wells: 'heatMapAggregatedFieldWells', dimensions: ['rows', 'columns'], measures: ['values'], label: 'Heatmap', icon: '▦', note: 'One row dimension, one column dimension and one measure. Missing combinations remain empty.' },
  box: { variant: 'boxPlotVisual', wells: 'boxPlotAggregatedFieldWells', dimensions: ['groupBy'], measures: ['values'], label: 'Box plot', icon: '⊞', note: 'Distribution of supplied values by group: min, interpolated quartiles, max. In the builder, add a sample dimension for distributions of group totals; these are not raw-record quartiles.' },
  wordCloud: { variant: 'wordCloudVisual', wells: 'wordCloudAggregatedFieldWells', dimensions: ['groupBy'], measures: ['size'], label: 'Word cloud', icon: 'Aa', note: 'One word dimension and one nonnegative weight. Deterministic horizontal layout; up to 80 words, longest words capped for legibility.' },
  histogram: { variant: 'histogramVisual', wells: 'histogramAggregatedFieldWells', dimensions: ['opensightSample'], measures: ['values'], label: 'Histogram', icon: '▟', note: 'Equal-width bins of supplied measure values. Builder samples are dimension-group totals, not raw records. Null samples are omitted.' },
  filledMap: { variant: 'filledMapVisual', wells: 'filledMapAggregatedFieldWells', dimensions: ['geospatial'], measures: ['values'], label: 'Filled map', icon: '▰', note: 'Requires country names matching the bundled overview map and one measure. No tiles or geocoding. Synthetic sales has no country field.' },
  pointMap: { variant: 'geospatialMapVisual', wells: 'geospatialMapAggregatedFieldWells', dimensions: ['latitude', 'longitude'], measures: ['values'], label: 'Point map', icon: '⌖', note: 'Requires latitude then longitude dimensions in degrees and one size measure. No tiles or geocoding. Synthetic sales has no coordinates; latitude/longitude wells are OpenSight extensions.' },
} as const;
export type ExtraKind = keyof typeof EXTRA_VISUALS;
export type VisualKind = 'bar' | 'line' | 'pie' | 'kpi' | 'table' | 'pivot' | ExtraKind;
export function extraKind(kind: string): kind is ExtraKind { return Object.hasOwn(EXTRA_VISUALS, kind); }
export const variantKinds: Record<string, VisualKind> = { pieChartVisual: 'pie', barChartVisual: 'bar', kpiVisual: 'kpi', lineChartVisual: 'line', tableVisual: 'table', pivotTableVisual: 'pivot', ...Object.fromEntries(Object.entries(EXTRA_VISUALS).filter(([kind]) => !['area','bar100'].includes(kind)).map(([kind, v]) => [v.variant, kind])) };
